import Head from 'next/head'
import { Button, CardActionArea, CardMedia, Typography, Grid } from '@mui/material'
import data from '@/utils/data'
import { useState } from 'react'

export default function Home() {
  let [you, setYou] = useState()
  let [imageBot, setImageBot] = useState("")
  let [result, setResult] = useState("")

  function handleChoose(e: any) {
    setYou(e.target.title)
  }

  if (!imageBot) {
    setImageBot("https://img.favpng.com/0/5/24/question-mark-royalty-free-stock-photography-clip-art-png-favpng-1btL9C6hEeRqEkK7WGVZE8gzK.jpg")
  }

  function getRandomId() {
    const run = (Math.floor((Math.random() * 3) + 1))

    if (!you) {
      setImageBot("https://img.favpng.com/0/5/24/question-mark-royalty-free-stock-photography-clip-art-png-favpng-1btL9C6hEeRqEkK7WGVZE8gzK.jpg")
      setResult("Choose the options")
    }

    if (run == 1 && you == "scissors") {
      setImageBot(data[0].image)
      setResult("Draw")
    }
    if (run == 1 && you == "rock") {
      setImageBot(data[0].image)
      setResult("You Win")
    }
    if (run == 1 && you == "paper") {
      setImageBot(data[0].image)
      setResult("Bot Win")
    }
    if (run == 2 && you == "scissors") {
      setImageBot(data[1].image)
      setResult("Bot Win")
    }
    if (run == 2 && you == "rock") {
      setImageBot(data[1].image)
      setResult("Draw")
    }
    if (run == 2 && you == "paper") {
      setImageBot(data[1].image)
      setResult("You Win")
    }
    if (run == 3 && you == "scissors") {
      setImageBot(data[2].image)
      setResult("You win")
    }
    if (run == 3 && you == "rock") {
      setImageBot(data[2].image)
      setResult("Bot Win")
    }
    if (run == 3 && you == "paper") {
      setImageBot(data[2].image)
      setResult("Draw")
    }
  }

  return (
    <>
      <Head>
        <title>Rock, Paper, Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography variant='h1' align='center' mb={3}>Rock, Paper, Scissors</Typography>
      <Grid container sx={{ justifyContent: "center", mb: 3 }}>
        <CardMedia
          component="img"
          image={imageBot}
          sx={{ width: 300, height: 300, borderRadius: 100 }}></CardMedia>
      </Grid>
      <Grid container direction={{ xs: "column", md: "row" }} sx={{ justifyContent: "center", gap: 5, mb: 3 }} >
        {data.map((value, index) => (
          <CardActionArea
            key={index}
            sx={{ width: 300, height: 300, borderRadius: 100 }}
            onClick={handleChoose}>
            <CardMedia
              component="img"
              title={value.name}
              image={value.image}
              sx={{ width: 300, height: 300, borderRadius: 100 }}></CardMedia>
          </CardActionArea>
        ))}
      </Grid>
      <Grid container sx={{ justifyContent: "center", mb: 3 }}>
        <Button onClick={getRandomId} variant={'contained'}>Play</Button>
      </Grid>

      <Typography variant='h1' align='center' mb={3}>{result}</Typography>
    </>
  )
}
